# -*- coding: utf-8 -*-
"""Synthetic Platform Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykVW0Tp6GaCmwU37X9aVIeBKuEeyIpaw
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

def generate_all_governance_data():
    np.random.seed(42) # Fixed seed for exact numerical reproducibility
    start_date = datetime(2026, 1, 1)
    num_days = 90

    channels_config = {
        'Meta Ads': {'spend_range': (800, 1500), 'cpm': 12.0, 'ctr': 0.015, 'cvr': 0.03, 'bias_range': (1.35, 1.45)},
        'Google Ads': {'spend_range': (1000, 2000), 'cpm': 15.0, 'ctr': 0.025, 'cvr': 0.04, 'bias_range': (1.20, 1.30)},
        'TikTok Ads': {'spend_range': (400, 900), 'cpm': 8.0, 'ctr': 0.010, 'cvr': 0.02, 'bias_range': (1.40, 1.55)},
        'Netflix Ads': {'spend_range': (600, 1200), 'cpm': 25.0, 'ctr': 0.008, 'cvr': 0.015, 'bias_range': (1.15, 1.25)}
    }

    platform_rows, mta_rows, holdout_rows = [], [], []

    for day_idx in range(num_days):
        current_date = (start_date + timedelta(days=day_idx)).strftime('%Y-%m-%d')

        for channel, config in channels_config.items():
            for campaign_num in range(1, 3):
                campaign_id = f"{channel.replace(' ', '_').upper()}_CMP_{campaign_num:02d}"

                # 1. Platform Reported Data
                spend = np.random.uniform(*config['spend_range'])
                impressions = int(round((spend / config['cpm']) * 1000))
                daily_ctr = np.clip(np.random.normal(config['ctr'], 0.002), 0.001, 0.10)
                clicks = int(round(impressions * daily_ctr))

                daily_cvr = np.clip(np.random.normal(config['cvr'], 0.005), 0.001, 0.20)
                true_conversions = int(round(clicks * daily_cvr))

                bias_multiplier = np.random.uniform(*config['bias_range'])
                reported_conversions = int(round(true_conversions * bias_multiplier))
                reported_revenue = round(reported_conversions * 75.0, 2)

                platform_rows.append({
                    'date': current_date, 'channel': channel, 'campaign_id': campaign_id,
                    'spend': round(spend, 2), 'impressions': impressions, 'clicks': clicks,
                    'reported_conversions': reported_conversions, 'reported_revenue': reported_revenue
                })

                # 2. MTA Model Output
                mta_dedup_factor = np.random.uniform(0.80, 0.90)
                mta_conversions = int(round(reported_conversions * mta_dedup_factor))
                mta_revenue = round(mta_conversions * 75.0, 2)

                mta_rows.append({
                    'date': current_date, 'channel': channel, 'campaign_id': campaign_id,
                    'mta_attributed_conversions': mta_conversions, 'mta_attributed_revenue': mta_revenue,
                    'mta_attribution_weight': round(mta_dedup_factor, 3), 'model_version': 'linear_decay_v1.2'
                })

                # 3. Holdout Experiment Data
                experiment_id = f"EXP_{campaign_id}"

                for group in ['control', 'treatment']:
                    geo_id = f"GEO_{group.upper()}_US"
                    is_treatment_period = (day_idx >= 30) and (group == 'treatment')
                    treatment_flag = 1 if is_treatment_period else 0

                    lift = 1.20 if is_treatment_period else 1.00
                    base_geo_conversions = int(round(true_conversions * 0.4))
                    holdout_conversions = int(round(base_geo_conversions * lift))
                    holdout_revenue = round(holdout_conversions * 75.0, 2)

                    holdout_rows.append({
                        'date': current_date, 'experiment_id': experiment_id, 'campaign_id': campaign_id,
                        'geo_or_cohort_id': geo_id, 'group_type': group, 'treatment_flag': treatment_flag,
                        'population_size': 500000, 'conversions': holdout_conversions, 'revenue': holdout_revenue
                    })

    benchmarks_data = [
        {'channel': 'Meta Ads', 'expected_roas_min': 1.5, 'expected_roas_max': 3.5, 'expected_cvr_min': 0.015, 'expected_cvr_max': 0.045, 'typical_incrementality_min': 0.40, 'typical_incrementality_max': 0.65},
        {'channel': 'Google Ads', 'expected_roas_min': 2.0, 'expected_roas_max': 4.5, 'expected_cvr_min': 0.020, 'expected_cvr_max': 0.060, 'typical_incrementality_min': 0.50, 'typical_incrementality_max': 0.75},
        {'channel': 'TikTok Ads', 'expected_roas_min': 1.0, 'expected_roas_max': 2.5, 'expected_cvr_min': 0.008, 'expected_cvr_max': 0.030, 'typical_incrementality_min': 0.30, 'typical_incrementality_max': 0.55},
        {'channel': 'Netflix Ads', 'expected_roas_min': 0.8, 'expected_roas_max': 2.0, 'expected_cvr_min': 0.005, 'expected_cvr_max': 0.020, 'typical_incrementality_min': 0.20, 'typical_incrementality_max': 0.45}
    ]

    pd.DataFrame(platform_rows).to_csv('RAW_PLATFORM_DATA.csv', index=False)
    pd.DataFrame(mta_rows).to_csv('RAW_MTA_OUTPUT.csv', index=False)
    pd.DataFrame(holdout_rows).to_csv('RAW_HOLDOUT_DATA.csv', index=False)
    pd.DataFrame(benchmarks_data).to_csv('BUSINESS_BENCHMARKS.csv', index=False)

generate_all_governance_data()

# Register CSV files as SQL views in DuckDB

!pip install duckdb -q

import duckdb

con = duckdb.connect(database=':memory:')

con.execute("CREATE VIEW RAW_PLATFORM_DATA AS SELECT * FROM 'RAW_PLATFORM_DATA.csv'")
con.execute("CREATE VIEW RAW_MTA_OUTPUT AS SELECT * FROM 'RAW_MTA_OUTPUT.csv'")
con.execute("CREATE VIEW RAW_HOLDOUT_DATA AS SELECT * FROM 'RAW_HOLDOUT_DATA.csv'")
con.execute("CREATE VIEW BUSINESS_BENCHMARKS AS SELECT * FROM 'BUSINESS_BENCHMARKS.csv'")

print("All 4 raw views registered successfully in DuckDB!")

# --- Step 1: Create Staging View ---
staging_sql = """
CREATE OR REPLACE VIEW STG_UNIFIED_MEASUREMENT AS
WITH stg_platform AS (
    SELECT date, channel, campaign_id, spend AS platform_spend,
           reported_conversions AS platform_conversions, reported_revenue AS platform_revenue
    FROM RAW_PLATFORM_DATA
),
stg_mta AS (
    SELECT date, campaign_id,
           SUM(mta_attributed_conversions) AS mta_conversions,
           SUM(mta_attributed_revenue) AS mta_revenue
    FROM RAW_MTA_OUTPUT
    GROUP BY date, campaign_id
),
stg_holdout AS (
    SELECT date, campaign_id,
           SUM(conversions) / 0.40 AS holdout_conversions,
           SUM(revenue) / 0.40 AS holdout_revenue
    FROM RAW_HOLDOUT_DATA
    WHERE group_type = 'treatment'
    GROUP BY date, campaign_id
)
SELECT p.date, p.channel, p.campaign_id, p.platform_spend, p.platform_conversions, p.platform_revenue,
       COALESCE(m.mta_conversions, 0) AS mta_conversions,
       COALESCE(m.mta_revenue, 0) AS mta_revenue,
       COALESCE(h.holdout_conversions, 0) AS holdout_conversions,
       COALESCE(h.holdout_revenue, 0) AS holdout_revenue,
       CASE WHEN h.holdout_conversions IS NOT NULL THEN 1 ELSE 0 END AS has_holdout_coverage
FROM stg_platform p
LEFT JOIN stg_mta m ON p.date = m.date AND p.campaign_id = m.campaign_id
LEFT JOIN stg_holdout h ON p.date = h.date AND p.campaign_id = h.campaign_id;
"""

# --- Step 2: Create Analytics View ---
analytics_sql = """
CREATE OR REPLACE VIEW ANALYTICS_MEASUREMENT_RECONCILIATION AS
WITH aggregated_campaigns AS (
    SELECT
        channel,
        campaign_id,
        SUM(platform_spend) AS total_spend,
        SUM(platform_conversions) AS total_platform_conversions,
        SUM(platform_revenue) AS total_platform_revenue,
        SUM(mta_conversions) AS total_mta_conversions,
        SUM(mta_revenue) AS total_mta_revenue,
        SUM(holdout_conversions) AS total_holdout_conversions,
        SUM(holdout_revenue) AS total_holdout_revenue,
        MAX(has_holdout_coverage) AS has_holdout_coverage
    FROM STG_UNIFIED_MEASUREMENT
    GROUP BY channel, campaign_id
)
SELECT
    channel,
    campaign_id,
    total_spend,
    total_platform_conversions,
    total_mta_conversions,
    total_holdout_conversions,
    ROUND(total_platform_revenue / NULLIF(total_spend, 0), 2) AS reported_roas,
    ROUND(total_holdout_revenue / NULLIF(total_spend, 0), 2) AS incremental_roas,
    ROUND(total_platform_conversions / NULLIF(total_holdout_conversions, 0), 2) AS inflation_ratio
FROM aggregated_campaigns;
"""

"""Analytics Measurement Reconciliation --- ^^"""

# --- Step 3: Create Governance View ---
governance_sql = """
CREATE OR REPLACE VIEW GOVERNANCE_CAMPAIGN_ALERTS AS
SELECT
    channel,
    campaign_id,
    total_spend,
    total_platform_conversions,
    total_holdout_conversions,
    reported_roas,
    incremental_roas,
    inflation_ratio,
    CASE
        WHEN total_holdout_conversions = 0 OR total_holdout_conversions IS NULL
            THEN 'NO_HOLDOUT_COVERAGE ⚠️'
        WHEN inflation_ratio >= 3.0
            THEN 'CRITICAL_INFLATION_WARNING 🚨'
        WHEN inflation_ratio >= 1.5
            THEN 'MODERATE_INFLATION 🟡'
        ELSE 'PASS ✅'
    END AS governance_status
FROM ANALYTICS_MEASUREMENT_RECONCILIATION;
"""

# Execute pipeline in logical dependency order
con.execute(staging_sql)
con.execute(analytics_sql)
con.execute(governance_sql)

# Display final results
df_governance = con.execute("SELECT * FROM GOVERNANCE_CAMPAIGN_ALERTS").fetchdf()
print("=== GOVERNANCE CAMPAIGN ALERTS ===")
print(df_governance)